### ISSUE TITLE
При изменении размеров окна происходит растяжение контролов

### ISSUE THREAD

**Issue by alexey-malov** [alexey-malov/ShapesApp#21]
Тулбар должен изменять свои размеры по ширине окна. Кнопки на нем должны оставаться неизменного размера

**Comment by oMystique** [comment]
Взял

**Comment by alexey-malov** [comment]
Выделить сущность CStage, композирующую окно и корневой CBaseControl
Выделить интерфейс IBaseControlContainer, реализуемый как Stage, так и BaseControl
Сделать класс CMainView, который прицепить к корневому CBaseControl
CMainView должен внутри себя создавать тулбар и управлять его размерами при изменении размеров окна
Внутри конструкторов классов-наследников CBaseControl нельзя использовать shared_from_this, т.к. объект еще не обернут в shared_ptr
