### ISSUE TITLE
Реализовать возможность выполнения действий после отцепления от родителя и после прицепления к новому родителю

### ISSUE THREAD

**Issue by alexey-malov** [alexey-malov/ShapesApp#27]
Добавить защищенные виртуальные методы в CBaseControl:
OnRemovedFromParent() - вызывается у дочернего элемента после того, как он был отцеплен от родителя
OnAddedToParent() - вызывается у дочернего элемента после того, как он был прицеплен к родителю
Эти методы не должны вызываться при изменении позции дочернего элемента внутри одного и того же Parent-а

При смене родителя сперва вызывается OnRemovedFromParent() (если родитель был), а потом OnAddedToParent()

Покрыть тестами

**Comment by Dzzirt** [comment]
Взял

**Comment by alexey-malov** [comment]
принято
