### ISSUE TITLE
Реализовать отложенное добавление Child-ов

### ISSUE THREAD

**Issue by alexey-malov** [alexey-malov/ShapesApp#28]
shared_from_this выбрасывает исключение bad_weak_ptr, если объект не обернут в shared_ptr
Это мешает добавлению child-ов во время работы конструктора
Предлагаемое решение:
При добавлении child проверять доступность shared_from_this и в случае недоступности запоминать операции по добавлению и удалению элементов.

Затем, после того, как объект был уже сконструирован выполнять отложенные операции

Сразу скажу, что эта задача не имеет 100% решения.
Например, у детей не будет GetParent() будет возвращать nullptr до тех пор, пока они окончательно не будут добавлены

Покрыть тестами данный функционал - создать тестовый наследник CBaseControl, который обернуть в unique_ptr
до тех пор, пока из unique_ptr не будет создан shared_ptr операции манипулирования детьми должны ограниченно работать (у детей parent будет нулевой), но после оборачивания в shared_ptr все должно встать на свои места

То есть при отложенном добавлении надо установить флажок, что мы не полностью прицеплены к родителю, а в операциях, использующих детей, проверять этот флажок и пробовать получить shared_from_this. В случае успеха говорить детям:

![image](https://cloud.githubusercontent.com/assets/6040682/14553814/5fa85882-02f1-11e6-8855-53bc8d730903.png)

**Comment by oMystique** [comment]
Взял

**Comment by alexey-malov** [comment]
Добавьте гласных букв в имена идентификаторов в тестах.
Подкину, мне не жалко: a, o, u, y, e, i,

**Comment by alexey-malov** [comment]
в именах тестов не должны фигурировать unique_ptr
лучше использовать термин "сконструированное состояние"
