### ISSUE TITLE
Разработать классы View для фигур

### ISSUE THREAD

**Issue by alexey-malov** [alexey-malov/ShapesApp#35]
Реализовать классы:
- TriangleShapeView
- RectangleShapeView
- EllipseShapeView

Вероятно, они должны быть наследниками CBaseControl

Ввести слой CCanvas (тоже наследник CBaseControl), позволяющий добавлять классы ShapeView

**Comment by pechischev** [comment]
взял

**Comment by alexey-malov** [comment]
Каждый класс ShapeView (и его наследники) не должны хранить свою копию frame
Они должны использовать фрейм, задаваемый в родительском классе

Frame задает координаты и размеры контрола в системе координат родительского контрола. При рисовании (0,0) соответствует верхнему левому углу контрола
